# Generated by Django 5.1.7 on 2025-03-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_authority_email_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authority_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
