# Generated by Django 5.1.7 on 2025-04-08 12:27

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('capacity', models.IntegerField()),
                ('room_type', models.CharField(choices=[('tutorial', 'Tutorial Block Room'), ('lecture_hall', 'Lecture Hall Room')], max_length=20)),
                ('accessories', models.JSONField(default=dict)),
                ('price_per_hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('academic', 'Academic'), ('nonacademic', 'Nonacademic')], default='nonacademic', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('booking_date', models.DateField()),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('accessories', models.JSONField(blank=True, default=dict)),
                ('cost', models.PositiveBigIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('booking_token', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('token_expiry', models.DateTimeField(default=datetime.datetime(2025, 4, 10, 12, 27, 33, 740982, tzinfo=datetime.timezone.utc))),
                ('approvals_pending', models.JSONField(default=dict)),
                ('authority_tokens', models.JSONField(default=dict)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.room')),
            ],
        ),
    ]
