# Generated by Django 5.1.7 on 2025-04-09 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="token_expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 11, 8, 45, 34, 901891, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
