# Generated by Django 5.1.7 on 2025-04-04 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 13, 40, 54, 91008, tzinfo=datetime.timezone.utc)),
        ),
    ]
