# Generated by Django 5.1.7 on 2025-04-04 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 9, 21, 27, 872013, tzinfo=datetime.timezone.utc)),
        ),
    ]
