# Generated by Django 5.1.7 on 2025-04-05 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 14, 15, 12, 884766, tzinfo=datetime.timezone.utc)),
        ),
    ]
