# Generated by Django 5.1.7 on 2025-03-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_booking_date_alter_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
