# Generated by Django 5.1.7 on 2025-04-05 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 11, 11, 13, 307378, tzinfo=datetime.timezone.utc)),
        ),
    ]
