# Generated by Django 5.1.7 on 2025-03-22 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval_token',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 21, 16, 57, 250744, tzinfo=datetime.timezone.utc)),
        ),
    ]
