# Generated by Django 5.1.7 on 2025-03-22 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_approval_token_booking_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 21, 21, 12, 537864, tzinfo=datetime.timezone.utc)),
        ),
    ]
