# Generated by Django 5.1.7 on 2025-04-10 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0008_alter_booking_token_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="token_expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 12, 9, 10, 6, 774410, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
