# Generated by Django 5.1.7 on 2025-03-25 11:30

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='approval_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 11, 30, 26, 330641, tzinfo=datetime.timezone.utc)),
        ),
    ]
