# <<<<<<< HEAD

# Generated by Django 5.1.7 on 2025-03-25 11:44


import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_approval_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
# <<<<<<< HEAD

            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 11, 44, 30, 154784, tzinfo=datetime.timezone.utc)),


        ),
    ]
