# Generated by Django 5.1.7 on 2025-03-25 11:33

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_holiday_alter_booking_approval_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approval_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 11, 33, 57, 234611, tzinfo=datetime.timezone.utc)),
        ),
    ]
