# Generated by Django 5.1.7 on 2025-03-25 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requested_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 6, 3, 55, 627207, tzinfo=datetime.timezone.utc)),
        ),
    ]
