# Generated by Django 5.1.7 on 2025-03-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_token_expiry'),
        ('bookings', '0012_alter_booking_approval_token_and_more'),
    ]

    operations = [
    ]
