# Generated by Django 5.1.7 on 2025-03-25 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_merge_20250325_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 11, 57, 53, 684852, tzinfo=datetime.timezone.utc)),
        ),
    ]
