
# Generated by Django 5.1.7 on 2025-03-25 11:57


import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
# <<<<<<< HEAD
        ('bookings', '0013_merge_20250325_1727'),
# =======
#         ('bookings', '0013_alter_booking_token_expiry'),
# >>>>>>> 98fb2e50128397a925b7dd759eaafdfdcb8d3d1b
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 11, 57, 53, 684852, tzinfo=datetime.timezone.utc)),

        ),
    ]
