<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-03-25 11:59
=======
# Generated by Django 5.1.7 on 2025-03-25 21:03
>>>>>>> 98fb2e50128397a925b7dd759eaafdfdcb8d3d1b

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 11, 59, 11, 548413, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 21, 3, 4, 687438, tzinfo=datetime.timezone.utc)),
>>>>>>> 98fb2e50128397a925b7dd759eaafdfdcb8d3d1b
        ),
    ]
