# Generated by Django 5.1.7 on 2025-03-25 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_booking_duration_alter_booking_need_ac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 12, 46, 14, 482441, tzinfo=datetime.timezone.utc)),
        ),
    ]
