# Generated by Django 5.1.7 on 2025-03-26 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_board',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_projector',
        ),
        migrations.AddField(
            model_name='room',
            name='accessories',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 11, 35, 45, 683783, tzinfo=datetime.timezone.utc)),
        ),
    ]
