# Generated by Django 5.1.7 on 2025-03-25 13:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requested_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 25, 13, 39, 19, 406096, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 13, 39, 19, 406219, tzinfo=datetime.timezone.utc)),
        ),
    ]
