# Generated by Django 5.1.7 on 2025-03-26 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_remove_room_has_ac_remove_room_has_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 13, 30, 33, 224575, tzinfo=datetime.timezone.utc)),
        ),
    ]
