# Generated by Django 5.1.7 on 2025-03-26 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='need_ac',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='need_projector',
        ),
        migrations.AddField(
            model_name='booking',
            name='accessories',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 13, 44, 53, 392638, tzinfo=datetime.timezone.utc)),
        ),
    ]
