# Generated by Django 5.1.7 on 2025-03-26 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_remove_booking_need_ac_remove_booking_need_projector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 18, 13, 35, 127073, tzinfo=datetime.timezone.utc)),
        ),
    ]
