# Generated by Django 5.1.7 on 2025-03-26 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 21, 1, 17, 881428, tzinfo=datetime.timezone.utc)),
        ),
    ]
