# Generated by Django 5.1.7 on 2025-03-26 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 23, 27, 39, 714470, tzinfo=datetime.timezone.utc)),
        ),
    ]
