# Generated by Django 5.1.7 on 2025-03-27 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_booking_token_expiry'),
        ('bookings', '0016_alter_booking_token_expiry'),
        ('bookings', '0019_alter_booking_requested_on_alter_booking_room_and_more'),
        ('bookings', '0031_alter_booking_token_expiry'),
    ]

    operations = [
    ]
