# Generated by Django 5.1.7 on 2025-03-27 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0032_merge_20250327_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 0, 26, 28, 486316, tzinfo=datetime.timezone.utc)),
        ),
    ]
