# Generated by Django 5.1.7 on 2025-03-27 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0033_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 17, 23, 1, 266649, tzinfo=datetime.timezone.utc)),
        ),
    ]
