# Generated by Django 5.1.7 on 2025-03-28 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0036_alter_booking_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 15, 0, 27, 50282, tzinfo=datetime.timezone.utc)),
        ),
    ]
